name: fish_environment
channels:
  - defaults
dependencies:
  - python=3.6.4
  - pyyaml=3.12
  - matplotlib=2.2.2
  - numpy=1.14.2
  - pandas=0.24.2
  - scikit-image=0.14.2
  - skan=0.8
  - scipy=1.0.0
  - imageio=2.6.1